### ISSUE TITLE
Quik will not record with Hero 13

### ISSUE THREAD

**Issue by skinn5** [gopro/labs#1083]
The record button is inoperable on the Quik app when I install GPL in the Hero 13.
Also I cannot change any of the parameters such as FOV, resolution in Quik. That field says “null.”

**Comment by dnewman-gpsw** [comment]
Sound like you need to do an factory reset, as Quik is work fine with HERO13 Labs in QA and my own person testing. There is a Labs release planned for next Tuesday that should much it more stable for initial setup (not requiring factory reset upon install.) But you can try it now: https://www.dropbox.com/scl/fi/0qr5b3cxv92u8hcbkujhz/LABS_HERO13_01_12_70.zip?rlkey=xq4j34pblroafn2py7rcdwii6&dl=1

**Comment by skinn5** [comment]
Thx for prompt response

I did factory reset but no solution

Downloaded update 2 to my sd card but when I put sd card in H13 the software did not load after I turned it back on

Am I missing something?

For example, should I be removing the QR codes already in camera anytime during this process?

**Comment by dnewman-gpsw** [comment]
Update procedure is the same as always, not impacted by anything.  Re-read the manual install instructions.

**Comment by skinn5** [comment]
David,

UR right. I started over and carefully followed all instructions and the app works fine.

Thank u.

I have a follow up question.

Is the minimum shutter speed necessary when using HS to avoid ghosting and jitter 240?

Does the number change depending on the frame rate?

Yesterday I used EXPN to set a minimum ss of 240 and set a minimum ISO 100 and a max 1600 and the result was overexposure probably 3 or 4 stops.

Any idea what caused the problem?

Jim

**Comment by dnewman-gpsw** [comment]
I think you wanted EXPX not EXPN.  They are confusing.  You may have forcing a longer shutter.  Use *EXPS=1 to see what the exposure is doing.

**Comment by skinn5** [comment]
Ur right-that fixed it

Thx

Is 240 the minimum SS I need for HS to prevent jitter and ghosting?

**Comment by dnewman-gpsw** [comment]
That is up to you, and the type of action you place on the camera.

**Comment by DemonViewLLC** [comment]
Loaded up this labs, but camera seems very slow to boot even though the only things I have active are the 24FPS and TUSB.

The other thing is the camera will now start to charge when plugged into a USB power supply but now after a few seconds, the red light turns off indicating the camera is no longer charging.

Camera would charge with no issues using these power supplies before (the Hero 12 is charging using them without issue).
I tried using the !reset command but that didn't help with much.  I was going to reload back on the production firmware but the link is currently down (due to release of new firmware tomorrow?).

Leaving the camera turned on and plugged in, battery level does indicate the camera is charging.

**Comment by dnewman-gpsw** [comment]
New Labs firmware is up.  I'm not seeing any issues with charging.  If you see any weirdness, try a factory reset with the new firmware. The Labs reset is !RESET, which is independent of factory reset.  TUSB might be impacting LED during changing, as that feature is often used for camera without batteries, I have never noticed.

**Comment by dnewman-gpsw** [comment]
All solved I believe.  Closing
