### ISSUE TITLE
mode change issue

### ISSUE THREAD

**Issue by ar8001** [gopro/labs#1099]
I created a code that should switch the camera mode to timelapse photo, to 5 seconds and wide lens.  Unfortunately the camera does not switch to the mode. What could be the problem?

Camera Gopro 11

Code: mTPp.10fWr0dR0

**Comment by dnewman-gpsw** [comment]
I'm sure this is because you don't have a preset for Timelapse Photo.  You likely have the default Timelapse Video present, so you can change this or create a new preset for TL Photo.  This is documented in the app and webpage 
<img width="440" alt="image" src="https://github.com/user-attachments/assets/92a78959-d14a-4b60-b064-dd77b5a36c03">
![image](https://github.com/user-attachments/assets/62ab101b-52bd-46ac-a70a-edac24a36b6a)

**Comment by ar8001** [comment]
I think there is a preset:

![image](https://github.com/user-attachments/assets/b254a8dd-a6ab-4859-9407-c4c75594b558)


![image](https://github.com/user-attachments/assets/f9aed86e-9543-4ccb-9426-d225a986354f)

**Comment by dnewman-gpsw** [comment]
It works on my HERO11s if I have a timelapse Photo preset.

**Comment by ar8001** [comment]
it is possible to create a preset by qr code?

**Comment by dnewman-gpsw** [comment]
It is not possible on HERO11, and there are limitations even on HERO12/13 for this.  For Timelapse Photo, that one mode needs to be create manually.
