### ISSUE TITLE
URGENT: Links BROKEN GoPro LABS Firmware Hero 11 and below

### ISSUE THREAD

**Issue by christiancorley** [gopro/labs#1209]
URGENT: Links BROKEN GoPro LABS Firmware.

Working links: Hero 13 and Hero 12

BROKEN:
All others... Hero 11, 10, etc. I made you a video showing the broken links...
Call for questions Christian Corley 913-481-4456
https://www.loom.com/share/140204fb67c2483e9141b949e0546be3?sid=5c58498d-d0c9-4cbd-8d34-8a607ce02c68

**Comment by dnewman-gpsw** [comment]
The links are not broken from this end, some browsers and maybe some ISPs are having issues with a double redirect, thinking it is a security issue (it is not.)  bit.ly points to github.com, and github sometimes redirects to a cached server at media.githubusercontent.com (the last step is github's doing, out of our control.) It is this double redirect is likely the issue for some locations or browsers. Others are discussing the issue here: https://github.com/gopro/labs/discussions/1157 with their workarounds. I've temporarily moved the HERO12 and 13 files (they are more popular), to a different server, but these are not cached, and could be very slow in some regions. 

I have just moved HERO11, but moving any more is a lot of work, particularly as these exiting links do work for most for downloaders. 

In your video you didn't go directly to the github downloads, you need to go into the folders for the downloads (you clicked on the same URL shorteners) Go to: https://github.com/gopro/labs/tree/master/docs/firmware/lfs

**Comment by dnewman-gpsw** [comment]
I have you worked it out?  Should this be closed?

**Comment by christiancorley** [comment]
NO, this is still broken. Only Hero 13 and 12 firmware works to download all others FAIL

Christian Corley
–––––––––––––––––––––––––––
mobile: 913-481-4456

**Comment by dnewman-gpsw** [comment]
You seem to have a caching (or similar) problem at your end, as HERO11 was also moved to the same server as H12 and H13, so you either didn't try H11 again, or your browser is using the old link. Try a different browser and/or use a VPN. We aren't seeing any impacts on the download data, so other users are successfully downloading all versions (up since xmas). This is not on our end. The redirects point directly to the github repo, which is this very site, so if you can access this message via a web browser, you can directly download all the Labs firmware.  https://github.com/gopro/labs/tree/master/docs/firmware/lfs  <- if you can't access this, contact your ISP or IT department.

**Comment by christiancorley** [comment]
David, I did learn that if I open the browser in PRIVATE mode then all works. Very strange… Customs will NEVER use a VPN or even think to use a Private browser. 

It sounds like you are saying this is not a GoPro dot com issue… but seems like it is to my team. But appreciate you looking

Thanks for the help!
Christian 

Christian Corley
–––––––––––––––––––––––––––
mobile: 913-481-4456

**Comment by dnewman-gpsw** [comment]
No GoPro servers are involved, just bit.ly and github.com, that is why can't be a gopro.com issue.  github.com is owned by Microsoft.

**Comment by christiancorley** [comment]
Thanks for the information. Happy New Year!

Christian Corley
–––––––––––––––––––––––––––
mobile: 913-481-4456
