### ISSUE TITLE
Extra Long time-lapse does not work for gopro 11 mini

### ISSUE THREAD

**Issue by JecO84** [gopro/labs#209]
Extra Long time-lapse does not work for gopro 11 mini ,there is no photo mode, you think it will be possible to put the photo mode of the gopro 11 on the mini with extra Long time-lapse ?

**Comment by dnewman-gpsw** [comment]
Not through Labs.  If the main firmware gets photo support, then Labs can control it. Plus, the Extra Long time-lapse feature is no longer favored due to reliability issues, it is much better to a video time lapse mode with a scheduled start and stop time like this example shows: https://gopro.github.io/labs/control/dailytl/
