### ISSUE TITLE
oMHSTP working, !MHSTP not

### ISSUE THREAD

**Issue by saaymeen** [gopro/labs#252]
I tried to set the histogram position to be on the front screen of the GP11 by default. I found that the MHSTP command works only with the option prefix but not permanently. Not sure if its a feature or a bug since the language specification suggests that o stands for only option prefix but the GoPro app offers a checkbox to make it permanent by replacing the o with an !.
If its intended, does that translate to other commands like MNR01 and MBITR as well?

works: oMHSTP=-1,-60,42
fails: !MHSTP=-1,-60,42

**Comment by dnewman-gpsw** [comment]
This is a unknown bug, that was just fixed on Mini, with the fix for HERO11 in a few week.

From the Mini release notes:
- Fixed !Mwxyz=-value, permanent metadata stores weren’t supporting negative values.

If you aren't using a boot command already you can do !MBOOT="oMHSTP=-1,-60,42"  as a workaround (or and this to your existing boot command.)

**Comment by dnewman-gpsw** [comment]
Fix now in release 2.10.70
