### ISSUE TITLE
GPS time synchronization does not sync year

### ISSUE THREAD

**Issue by kouyoumin** [gopro/labs#444]
I'm using HERO11 2.10.70 without internal battery and powered by volta. Date resets everytime so I always wait for GPS before use. I found that months to seconds are synced correctly except year is stuck at 2016. Doesn't GPS synchronize year?

**Comment by dnewman-gpsw** [comment]
You are correct, this is a bug.  It will be fixed in the next update.  Now for a possible workaround.  

If you aren't using a boot command you could do !MBOOT="oT230715"  This will make the camera set a date with a valid year upon boot.  Then the !MSYNC=1 will update the month, day, hour, minute and second correctly with a GPS lock.

**Comment by dnewman-gpsw** [comment]
Now fixed in in v2.12.70 release August 10, 2023
