### ISSUE TITLE
Does Motion Detect work with oDO/LCD Off command on GP11?

### ISSUE THREAD

**Issue by anteedrew** [gopro/labs#496]
Hi David, I have a GP11 on Labs v2.12.70. As the title reads, I'm unable to get "oDO"(LCD Off Now) to work with Motion Detect in the same command string.

oDO works on its own, and a Motion Detect command of "!SM5H5!R" works on its own, but when I combine into "!SM5H5!RoDO" it seems to completely ignore the LCD off command. Any ideas on any fix or workaround?

I would just let the screen go to sleep after 1 minute, but it wakes the screen every time new motion is detected.

Thanks for any tips or insight you might have, I appreciate all the work you and your team have put into the Labs fireware for GP!

**Comment by anteedrew** [comment]
Thanks David! Any idea how long an update like this might take to reach live firmware? I have a trip in about 1 month where I'd like to utilize a fully functional oDO!SM5H5!R

As a side note, I'm sparingly able to get my desired results by using oDO first, and while the screen is off, I use !SM5H5!R to start the motion detection. I use the official GoPro app to monitor when it starts/stops recording. _Sometimes_ the screen will stay off when Motion Detect starts, but it's too inconsistent for me to have faith that it'll work when I need it to.

**Comment by dnewman-gpsw** [comment]
The screen start with the start capture, so it is core to the camera (I looked into it.)  Just set the bright to 10% (oB1) and auto off to 1 minute (oS1).  The only way to have the screen off within a couple of seconds is to use a new style script rather than the old !SMx style motion capture. 

![image](https://github.com/gopro/labs/assets/10856084/6c2ad386-dc96-4fba-a107-cf28e6427cbe)

Generated:
![MotionCapture-8_22_2023, 15_48_34](https://github.com/gopro/labs/assets/10856084/7406aeb6-b56b-483a-94d7-6c03727f0532)
