### ISSUE TITLE
Noise reduction and very large chapters GoPro Max?

### ISSUE THREAD

**Issue by snigel** [gopro/labs#572]
In the extensions page, GoPro Max isn't mentioned, even though it now supports the BITR command.
Are there more commands that are supported for Max but not yet documented?

I'm interested in very large chapters, such as 64GB and reducing noise reduction.

**Comment by dnewman-gpsw** [comment]
The NR01 (noise reduction control) was developed for GP2 only, so it can't working on MAX.

The very large chapters, beyond 12GB, is also not possible on MAX.  The large chapter hack was achieving 12GB from 4GB indexes using delta compression, so that is had the same memory needs (this is why it was 12, not 16GB.)  On GP2 cameras the memory increases so that chapters up 64GB was possible without all the delta compression hacks used on GP1.

**Comment by snigel** [comment]
Thank you, very informative.

Can I assume Max supports the same commands as another GP1 camera when the setting is applicable? Trying to grasp what should work and shouldn't among all the commands.

GP1 = Hero 7, 8, 9 and Max, right?

**Comment by dnewman-gpsw** [comment]
GP1 is those cameras (and HERO6).  MAX being the only 360 camera, had some extras and some subtractions, and as the only GP1 camera GoPro still sells, it got a more resent Labs update with the advanced scripting support:  H11,12 and MAX only.
