### ISSUE TITLE
GoPro Labs 2.4A PowerSupply Warning

### ISSUE THREAD

**Issue by TimZingler** [gopro/labs#687]
Hi Guys,

I use a Anker 325 Power Bank (PowerCore 20K) to power the GoPro onsite where theres no constant power. With normal Firmware and a USB KeepALive Device this works with no faults even with the long cable. But with the Labs Firmware - in 9/10 cases there comes the too less power warning. But the Power Bank is capable of delivering that and with the standard firmware it works without problems.

**Comment by dnewman-gpsw** [comment]
use !MTUSB=1  trust USB

You didn't mention the camera model.  This occurs, by design, in mainline firmware on the HERO10 later releases and newer cameras.  Camera communicate with the power supply to determine the available current limits, it you have a bad cable or a Keepalive circuit that doesn't pass all the data lines, you will see this problem.  Labs solves this with the Trust USB command, where you are asserting that there is sufficient power.   https://gopro.github.io/labs/control/extensions/

**Comment by TimZingler** [comment]
Oh thx, I will try.
Its a GoPro HERO 11

I just wonder why it does happen on Labs but not with the Original Firmware.

**Comment by dnewman-gpsw** [comment]
It happens on stock firmware, as the feature was added to Labs to fixed the issue.

**Comment by TimZingler** [comment]
Oh okay, but i never stumbled upon it.
