### ISSUE TITLE
Hero 10 motion detection: LCD can be turned OFF

### ISSUE THREAD

**Issue by wslany** [gopro/labs#77]
As mentioned on [https://gopro.github.io/labs/control/motion/](https://gopro.github.io/labs/control/motion/), on the Hero 10 the LCD needs to stay ON for motion detection to work. For extended motion captures, the page suggests to set the LCD brightness to 10%. This limitation does not apply to earlier models. 

However, LCD at 10% will still drain the battery and thus reduce the time one can use the motion detection recording. Is there a workaround, or is it planned to fix this for the Hero 10?

Thanks a lot for the motion detection feature.

**Comment by dnewman-gpsw** [comment]
No plan, it was architectural difference on HERO10 that requires the LCD on for motion detection.

**Comment by wslany** [comment]
Thank you. Can at least the front facing LCD be turned OFF? Also, is it possible to set the rear LCD to a smaller percentage? 10% still seems rather bright to me.

**Comment by dnewman-gpsw** [comment]
The front LCD does not have to be on, you can disable it with the menus or with qr command **oF0**   10% brightness is the lowest offered, and the command reflect that.

**Comment by dnewman-gpsw** [comment]
Not an issue on HERO11.  Works fine with LCD off.

**Comment by wildplaceswildhikes** [comment]
Hi there! I've been using gopro labs with my gopro 9 and gopro 10 for two years now. Great coding and really helpful features. 

As a wildlife videographer I use the motion detection to film animals without my presence. But I have a HUGE problem - the batery drainage. 

I use a 30 000 mah powerbank, and with the minimun 10% LCD brightness I still only have the camera on for about 24 to 30h ( depends on the amount of recorded videos, and temperature ) 

I didnt knew I could turn the LCD off so my questions are 

- What models am I able to use the motion detection and have the LCD off? I will be selling my Gopro10 to buy the 12/13 so I would really need to know this information. 

- Also any advice how to power the camera for more than 24/30 hours? After testing a few weeks with my 30 000 Mah powerbank I bought a 50 000 Mah from another brand, but when the powerbank reaches 30% capacity it turns off. The ideal length for having the camera in the field would be at least 72 to 96 hours 

- On most of the places I set up the gopro I'm not able to connect to a solar panel because its dense woods with tall trees, and running cables up them its not possible. I think my best option is to stick with one of the Gopro models that I can turn off the LCD and use a large batery. 

- Having the LCD turned off will make me loose a few seconds before the camera ''wakes up'' and starts recording? 

- For DSLR and Mirrorless cameras there are motion detection sensors that can be used to photograph and record video, and they work like: the camera enters sleeping mode and the motion sensor wakes the camera a sends another signal to shoot ( photo or video ) the sensor I know its https://store.camtraptions.com/collections/camera-traps/products/wireless-pir-motion-sensor?variant=15385707872339 but because go pro doesnt have a trigger input doenst work with it, OR is there a way to disassemble the gopro a connect a trigger port to it? Rad idea I had for a while but would like to share it here. 

Here you can see an amazing result I had with this setup! 

CHEERS! 


![Image](https://github.com/user-attachments/assets/591a252d-c37d-4a25-9cf5-5ac209e2b717)

**Comment by dnewman-gpsw** [comment]
Only the HERO10 had this limitation, 8, 9, 11, 12 or 13 do not.  However the LCD power usage in not very high, having the LCD off may only increase runtimes 10-15%. HERO12 and 13 are slightly more efficient. However using a scene detection from video camera is not the most efficient way to do it, it is just the most responsive solution.  

You could use an external trigger, wake the camera and record.  The only issue is the boot time for the GoPro, the best is H13 at about 5 seconds from a power trigger to capture.  You could open a camera and wire in a button to trigger quickcapture, but this is a 3 second delay.

**Comment by wildplaceswildhikes** [comment]
Hello! And thanks for the feeback man! 

Well so when you say HERO12 is more efficient you mean the device standby and record mode use less power? 

I'm undecided betwen buying the 11 or 12 for this purpose. 

About the external trigger to wake the camera and record does anybody knows any trigger that can make this happen? With that possibility a 50 000 MAH powerbank might last me a few days in the field! Its really no feasible to go there change the powerbank everyday. 

Does anybody know of an efective external power suply? Or a possibility of connecting two 50 000 MAH powerbanks together? Just wondering! 


CHEERS

**Comment by dnewman-gpsw** [comment]
You should be asking new questions in an open thread.  Here: https://github.com/gopro/labs/discussions

HERO12 and 13 (not so much 11) are more power efficient in some video modes for sure, capture is more efficient, standby might be.  

The trigger is simply adding a switch to turn on USB power, but converting a external motion sensor to switch on USB power will be up to you to investigate (just a relay I expect.)   

Use battery like this: https://www.amazon.com/12V-50Ah-Battery-12V-Protection-Replacement/dp/B0D7P999KD
with 12V to USB buck convertor https://www.amazon.com/PlusRoc-Waterproof-Converter-Compatible-Raspberry/dp/B09DGDQ48H

With the camera always on, this will last a bit over a week.

Do you need to record at night?  If you only motion detect in daylight you could double the runtime.
