### ISSUE TITLE
Feature Request: GPS lock before starting recording in quick capture mode

### ISSUE THREAD

**Issue by aalse** [gopro/labs#82]
I would like to be able to configure quick capture mode so it waits for a GPS lock before starting to record footage for x duration and then shutsdown. This would be very useful for motorcycling use cases where in the tap of a button I can get the camera to power on, get a GPS lock, record for 1 minute, and then powers off.

**Comment by dnewman-gpsw** [comment]
Interesting.  Need to think on this.

**Comment by dnewman-gpsw** [comment]
For HERO11 Labs 1.20.70, there is a new command for waiting for GPS lock.  This maybe added to HERO10, but likely not any older models.
  `!Dx command waits for GPS lock with a DOP less than x.`
While is it not for Quick Capture, it could be used in a way you want, it you press power rather than shutter. The power on action can be enhancement with a boot command (see BOOT https://gopro.github.io/labs/control/extensions/) 

!MQRDR=1!MBOOT="!Lboot"!SAVEboot=mV!D12!S!60E!1O

In this command is sets up the boot action, which all sets mode video (mV), wait for GPS with DOP of 12.0 (!D12), then start capture (!S), end after a minute (!60E), and power off (!1O).

More more discussion on this feature, please consider posting here https://github.com/gopro/labs/discussions

**Comment by aalse** [comment]
@dnewman-gpsw thank you for considering this request and all your hard work that has made it possible! I have a Hero 10 Black so I guess I'll have to wait a bit or upgrade to the Hero 11. Using the power button instead of the quick capture button doesn't really make a difference to me since the end outcome is the same.
