### ISSUE TITLE
Unknown error upon media list request when using Trust USB

### ISSUE THREAD

**Issue by pavlosharhan2** [gopro/labs#986]
Device: GoPro10, latest labs firmware

When you use trust USB feature and the camera goes to hibernation state so only BLE module is active, once you wake camera up via bluetooth connection - you get "Unknown error" in response to gopro/media/list, and only power cycling helps with that. GoPro quick can't show the media too.

Steps to reproduce: 
- Enable Trust USB
- Remove internal battery, power the camera from the cable
- Turn the camera on/off via side button
- Connect to camera via ble so it wakes up
- Now you will always get unknown error in response to gopro/media/list

My workaround is to use WakeOnPower feature so the gopro doesn't go to sleep

Expected behavior is that there is no reason the camera should not be able to response with It's media list if the camera was waken up from sleep

**Comment by dnewman-gpsw** [comment]
It is unlikely the TUSB command, as all that does is lie to the rest of the camera with one line of code.
if(g_trust_usb_power) *max_current = 3000;
Which sets the power source input to a current limit of 3000mA, if it was otherwise unknown.  If you have a compatible power source, you should not need TUSB.

Wake of Power, still puts the camera to sleep.  So I expect this is something else.  

Can you see if this happen on stock firmware?  You will need a USB C native power source.
